### ISSUE TITLE
[Configs] 깃헙 세팅 

### ISSUE THREAD

**Issue by leobang17** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#1]
## Issue
- 깃허브 세팅 할게용

## ToDo
- [x] 이슈 템플릿 생성 
- [x] PR 템플릿 생성 
  - [x] PR 템플릿을 멀티 템플릿에서 단일 템플릿으로 변경
- [x] CI/CD
