### ISSUE TITLE
[Feature] Realm setups, 데이터 모델링 

### ISSUE THREAD

**Issue by leobang17** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#14]
## 💡 Issue

Realm을 설치하고 데이터 모델링을 합니다.

## ☑️  Todo
- [x] Realm with CocoaPods
  - [x] gitignore 수정
  - [x] github action workflow 수정
  - [x] Realm dependency 추가
- [x] Data Modeling 
  - [x] 필요한 기능 정의 
  - [x] Model 정의 
 

## 📕 References
- [Github action](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions)
- [CocoaPods CI/CD](https://void0306.tistory.com/3)
- [Realm Docs](https://www.mongodb.com/docs/realm)

**Comment by leobang17** [comment]
끄 ~ 읕 ~
