### ISSUE TITLE
[Feature] 메인에서 편지작성 뷰 까지 가기 위한 flow

### ISSUE THREAD

**Issue by dgfghsjd** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#19]
## 💡 Issue
편지 작성 버튼 이후의 flow에 대해 구현하기
작성하기, 임시저장하기

## ☑️  Todo
- [x] 브랜치 만들기

- [x]  편지의 작성
  - [x] 네비게이션 바 안에 작성 모달 열리는 버튼 넣기
  - [x] 네비게이션 뷰를 모달로 띄우기
  - [x] 편지 작성화면 레이아웃 구현
    - [x] 갤러리와 연결 & 사진 실제로 불러오기
    - [x] 타이틀 공간
    - [x] 내용공간
    - [x] 작성날짜 불러오기
    - [x] 네비게이션 안에 작성 완료
    - [x] 네비게이션 안에 임시저장 Action sheet
  - [x] Action sheet 실제 기능 작동하도록 함
  - [x] 편지 작성완료/임시저장 하면 실제로 리스트에 쌓이도록 구현

- [x] 편지의 수정
  - [x] 편지의 상세보기 화면에서 작성하는 필드만 바뀌도록
  - [x] 수정 완료시 alert
