### ISSUE TITLE
[Feature] 메인뷰에서 천국뷰 연결 관련: 이동 조건, 연결 애니메이션, 안내

### ISSUE THREAD

**Issue by EuniceNam** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#24]
## 💡 Issue

메인뷰에서 천국뷰로 이동하는 동작 관련입니다.
- 메인뷰에서 천국뷰 이동할 때 아래로 내려오는 전환방식 적용하기
- 메인뷰에서 천국뷰로 이동하는 제한조건 반영하기
- 메인뷰에서 천국뷰로 이동할 수 없을 때 안내 메시지 띄우기

## ☑️  Todo
- [ ] 천국뷰 이동 애니메이션 커스텀
- [ ] 천국뷰 이동 조건 반영: 오늘 꽃을 고른 적이 있다. 
- [ ] 천국뷰 이동 못할 때 안내 알러트
