### ISSUE TITLE
[Feature] 꽃뷰 구현

### ISSUE THREAD

**Issue by siro96-01** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#28]
## ☑️  Todo
- [x] 꽃뷰 UI 구현
- [x] Carousel 동작
- [x] Carousel 위치 버그 수정
- [x] table control로 밑에 segment 추가
