### ISSUE TITLE
[Feat] 메인뷰 UI

### ISSUE THREAD

**Issue by EuniceNam** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#3]
## 💡 Issue
메인뷰

## ☑️  Todo
- [ ] MainViewController, NavigationController
- [ ] 꽃, 편지, 설정 버튼 구현
  - [ ] 재사용 뷰 써보기 (불확실) 
  - [ ] 버튼에 꽃, 편지 프리뷰 반영 
- [ ] 랜덤 위로(+투두) 문구 구현
- [ ] 천국뷰 올라가는 버튼과 제스쳐 입력 받기
  * (당일 설정 꽃 없을 때 알러트, 천국뷰 올라가는 애니메이션은 다른 이슈로)
- [ ] 디자인에 맞게 다듬기
