### ISSUE TITLE
[Feat] 메인뷰 렘 연결

### ISSUE THREAD

**Issue by EuniceNam** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#39]
## 💡 Issue

메인뷰에서 렘과 연결되어야할 것을 연결합니다

## ☑️  Todo
- [ ] 오늘 헌화를 했는지 관련 연결
- [ ] 뷰 이동시 상태 변경: 헌화, 편지
- [ ] 현재 꽃, 현재 보낼 편지 숫자 반영
