### ISSUE TITLE
[Feat] Realm 기능 추가 / 리팩토링 

### ISSUE THREAD

**Issue by leobang17** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#44]
## 💡 Issue

Realm 기능 추가하고 리팩토링 필요한 부분 수행.

## ☑️  Todo
- [x] .realm의 경로 print하는 생성자 
- [x] recent flowers 안나오는 오류 해결 + recent flowers 7개로 제한
- [x] send 할 때 임시저장도 같이 보내지는 오류 해결
- [x] MainView에서 Temporary는 count에서 제외
- [x] MainView에서 천국뷰로 갈 수 있는지도 확인하기
- [x] 앱 설치할 때 기본 데이터 넣어주기 
- [x] 펫 update, delete
- [x] 나이 계산하는 로직 추가
 

## 📕 References
- [Open a Realm file](https://www.mongodb.com/docs/realm/studio/open-realm-file/)
- [Configure & Open a Realm](https://www.mongodb.com/docs/realm/sdk/swift/realm-files/configure-and-open-a-realm/)
