### ISSUE TITLE
[Feat] 천국뷰 UI 및 기능 구현

### ISSUE THREAD

**Issue by LentoAssai** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#45]
## 💡 Issue
천국뷰 UI, 기능 구현

## ☑️  Todo
- [ ] 천국뷰 UI 구현
- [ ] 천국뷰 사진 추가 기능 구현
- [ ] 천국뷰에서 편지 리스트 뷰로 이동

## 📕 References
