### ISSUE TITLE
[Feat] Realm 요구사항 반영 및 개선점 추가 

### ISSUE THREAD

**Issue by leobang17** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#74]
## 💡 Issue

Realm 요구사항 반영 및 개선점 추가 

## ☑️  Todo
- [x] pet update DTO에 name 추가 + pet result DTO에 birth 추가
- [x] flower 선택할 때 log가 추가되지 않도록 
- [x] updateFlower 수정
- [x] preset 데이터 채워넣기
