### ISSUE TITLE
[Chore] 프로젝트 폴더링 세팅

### ISSUE THREAD

**Issue by jola7373** [DeveloperAcademy-POSTECH/MC3-Team10-TenTen#8]
## 💡 Issue
프로젝트 내부 폴더링 나누기

## ☑️  Todo
- [x] Screen 폴더 생성
- [x] Network 폴더 생성
- [x] Global 폴더 생성
